export const CHANGELOG = [
  {
    version: '1.1.9',
    date: 'March 2026',
    items: [
      'Reduced dashboard latest transaction section to a compact snapshot (top 3) to cut cognitive load',
      'Added contextual dismissible guide hints on Transactions and Bills for in-flow feature education',
      'Added local reminder infrastructure with settings controls, notification permission flow, and throttled dashboard alerts',
      'Added undo flows for transaction and bill deletions using a short delayed-delete window with one-tap restore',
      'Added Phase 3 reconciliation workspace with queue metrics, quick category correction, and one-tap reviewed state',
      'Added Monthly entry card that surfaces pending reconciliation count and deep-links into the review workspace',
      'Added advanced Monthly budget variance panel with projected month-end delta and category risk buckets',
      'Added GitHub Actions CI to enforce build checks on PRs and run runtime verification when Supabase secrets are configured',
      'Added recurring transactions engine with schedule generation, form controls, and list/export visibility',
      'Added optional dev-only query timing traces via localStorage flag kosha:trace-queries=1',
      'Fixed liabilities realtime E2E test flake by cleaning up attempt timers to prevent false post-pass failures',
    ],
  },
  {
    version: '1.1.8',
    date: 'March 2026',
    items: [
      'Added immutable financial audit-event logging for transaction and bill mutations (add, edit, delete, mark-paid)',
      'Added Dashboard Recent Activity feed powered by financial_events for a transparent mutation timeline',
      'Made Recent Activity entries actionable with deep links that open and highlight the related transaction or bill',
      'Added deploy-readiness verification script to validate env setup, schema surface, and required Supabase RPC availability before release',
      'Further hardened liabilities realtime E2E by removing event-id race conditions and adding resilient retry backoff',
      'Updated CI pipeline to run deploy-readiness as an explicit gate before runtime verification tests',
      'Documented CI policy and recommended branch-protection required checks for deployment discipline',
      'Added pull request template with mandatory verification evidence and release-checklist items',
      'Added CODEOWNERS for critical paths to enforce targeted review ownership on sensitive changes',
      'Added GitHub issue templates for bug reports and release blockers with structured triage fields',
      'Added one-command release candidate verification script with final PASS/FAIL summary output',
      'Documented formal phase-status tracking and adoption-quality release roadmap (1.2.0 to 1.4.0) in README',
      'Added in-app Guide page with start checklist, feature map, playbooks, and FAQ/privacy guidance',
      'Added dashboard entry point and dismissible first-use hint for faster feature discovery',
    ],
  },
  {
    version: '1.1.7',
    date: 'March 2026',
    items: [
      'Reduced initial app bundle by route-splitting Dashboard, Onboarding, and NotFound pages',
      'Unified mixed icon usage per file and cleaned redundant icon imports',
      'Extracted shared navigator and skeleton components to reduce duplication',
      'Optimized Dashboard render paths by consolidating bill-derived calculations',
      'Tuned transaction and liability query freshness windows to reduce redundant remount/focus refetches',
      'Fixed transaction and bills lists not appearing immediately across pages after closing add/edit dialogs',
      'Hardened add/edit/delete/mark-paid mutation flows with race-safe cache reconciliation and guarded background refreshes',
      'Improved transaction and bills sheet UX on mobile with stable chip layouts and sticky primary action bars',
      'Added mutation stress runtime test coverage to validate rapid transaction and liability mutation consistency',
      'Added CSV export for both Transactions and Bills with robust encoding for spreadsheet compatibility',
    ],
  },
  {
    version: '1.1.6',
    date: 'March 2026',
    items: [
      'Fixed stale transaction and bills lists — now refresh immediately after add, edit, delete, and mark-paid actions',
      'Moved mutation invalidation into shared transaction/liability hooks for consistent server-truth updates across pages',
      'Fixed transaction row delete spinner getting stuck in edge cases',
      'Added Forgot Password flow with reset email support from Login',
      'Added Set New Password flow after reset-link redirect',
      'Added post-reset success confirmation with automatic redirect back to Sign in',
    ],
  },
  {
    version: '1.1.5',
    date: 'March 2026',
    items: [
      'Fixed "Not signed in" error when adding transactions or bills on first app open',
      'Dialogs now close instantly after saving — no more 1–3 second freeze',
      'Transaction list, balance, and monthly summary update immediately after any change',
      'Bills now use an atomic database operation — no risk of mismatched data on payment',
      'Running balance calculation moved server-side — faster and scales with history',
      'Monthly and yearly summaries now computed on the server — significantly faster load',
      'Fixed duplicate network requests triggered after every local change',
      'Search in Transactions no longer triggers unnecessary database count queries',
      'Dashboard sections now update independently — changing one no longer redraws all',
      'Fixed month rollover on Dashboard not detecting until up to 60 seconds after midnight',
      'Reduced unnecessary re-renders across Dashboard, Monthly, Analytics, and Transactions',
    ],
  },
]