/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'kosha-bg':            '#F2F2F7',
        'kosha-bg-2':          '#FFFFFF',
        'kosha-surface':       '#FFFFFF',
        'kosha-surface-2':     '#F2F2F7',
        'kosha-border':        '#E5E5EA',
        'kosha-border-strong': '#C7C7CC',
        'brand':               '#007AFF',
        'brand-dark':          '#0062CC',
        'brand-container':     '#EBF4FF',
        'brand-on':            '#0040A0',
        'income':              '#34C759',
        'income-bg':           '#EDFAF1',
        'income-text':         '#1A7A35',
        'income-border':       '#A8E6B8',
        'expense':             '#FF3B30',
        'expense-bg':          '#FFF0EF',
        'expense-text':        '#CC0000',
        'expense-border':      '#FFB3AF',
        'invest':              '#007AFF',
        'invest-bg':           '#EBF4FF',
        'invest-text':         '#0040A0',
        'invest-border':       '#99CCFF',
        'repay':               '#FF9500',
        'repay-bg':            '#FFF5E6',
        'repay-text':          '#A05000',
        'repay-border':        '#FFCC80',
        'ink':                 '#000000',
        'ink-2':               '#3C3C43',
        'ink-3':               '#8E8E93',
        'ink-4':               '#C7C7CC',
        'on-grad':             '#FFFFFF',
        'on-grad-2':           '#FFFFFFBF',
        'warning':             '#FF9500',
        'warning-bg':          '#FFF5E6',
        'warning-border':      '#FFCC80',
        'warning-text':        '#A05000',
        'success':             '#34C759',
        'danger':              '#FF3B30',
      },
      fontFamily: {
      display: ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'Inter', 'system-ui', 'sans-serif'],
      sans:    ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Text',    'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'hero':    ['44px', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display': ['28px', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'title':   ['20px', { lineHeight: '1.3',  letterSpacing: '-0.01em' }],
        'label':   ['11px', { lineHeight: '1.4',  letterSpacing: '0.06em' }],
      },
      borderRadius: {
        'card':    '16px',
        'card-lg': '20px',
        'hero':    '24px',
        'chip':    '8px',
        'pill':    '9999px',
      },
      boxShadow: {
        'card':       '0 2px 8px rgba(0,0,0,0.08), 0 0 0 0.5px rgba(0,0,0,0.04)',
        'card-md':    '0 4px 16px rgba(0,0,0,0.10), 0 0 0 0.5px rgba(0,0,0,0.04)',
        'card-lg':    '0 8px 32px rgba(0,0,0,0.12), 0 0 0 0.5px rgba(0,0,0,0.04)',
        'apple-card': '0 20px 60px rgba(0,0,0,0.18), 0 8px 20px rgba(0,0,0,0.10)',
        'fab':        '0 4px 16px rgba(0,122,255,0.35)',
        'focus':      '0 0 0 3.5px rgba(0,122,255,0.30)',
        'urgent':     '0 2px 8px rgba(255,59,48,0.20), 0 0 0 0.5px rgba(255,59,48,0.15)',
        'warn':       '0 2px 8px rgba(255,149,0,0.20), 0 0 0 0.5px rgba(255,149,0,0.15)',
      },
      keyframes: {
        'sheet-in': {
          '0%':   { transform: 'translateY(100%)' },
          '72%':  { transform: 'translateY(-4px)' },
          '100%': { transform: 'translateY(0)' },
        },
        'fade-in':   { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'slide-up': {
          '0%':   { transform: 'translateY(12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)',    opacity: '1' },
        },
        'swipe-out': {
          '0%':   { transform: 'translateX(0)',     opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '0' },
        },
        'scale-in': {
          '0%':   { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)',    opacity: '1' },
        },
      },
      animation: {
        'sheet-in':  'sheet-in 0.40s cubic-bezier(0.32,0.72,0,1) forwards',
        'fade-in':   'fade-in 0.2s ease forwards',
        'slide-up':  'slide-up 0.28s ease forwards',
        'swipe-out': 'swipe-out 0.22s ease forwards',
        'scale-in':  'scale-in 0.22s ease forwards',
      },
    },
  },
  plugins: [],
}